typedef struct{
  int fnx,fny,fnz;
  int hnx,hny,hnz;
  int ghx,ghy,ghz;
}global_info;



typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_11;
  double *state_oldu_11;
  double *state_oldv_11;
  double *state_oldjab_11;
  double *state_oldjab5_11;
  double *state_oldjab6_11;
  double *state_oldjab7_11;
  double *state_olduc_11;
  double *state_oldvc_11;
  double *state_newh_11;
  double *state_newu_11;
  double *state_newv_11;
  double *state_newjab_11;
  double *state_newjab5_11;
  double *state_newjab6_11;
  double *state_newjab7_11;
  double *state_newuc_11;
  double *state_newvc_11;
} updateState_0_0_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_12;
  double *state_oldu_12;
  double *state_oldv_12;
  double *state_oldjab_12;
  double *state_oldjab5_12;
  double *state_oldjab6_12;
  double *state_oldjab7_12;
  double *state_olduc_12;
  double *state_oldvc_12;
  double *state_newh_12;
  double *state_newu_12;
  double *state_newv_12;
  double *state_newjab_12;
  double *state_newjab5_12;
  double *state_newjab6_12;
  double *state_newjab7_12;
  double *state_newuc_12;
  double *state_newvc_12;
} updateState_0_1_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_13;
  double *state_oldu_13;
  double *state_oldv_13;
  double *state_oldjab_13;
  double *state_oldjab5_13;
  double *state_oldjab6_13;
  double *state_oldjab7_13;
  double *state_olduc_13;
  double *state_oldvc_13;
  double *state_newh_13;
  double *state_newu_13;
  double *state_newv_13;
  double *state_newjab_13;
  double *state_newjab5_13;
  double *state_newjab6_13;
  double *state_newjab7_13;
  double *state_newuc_13;
  double *state_newvc_13;
} updateState_0_2_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_21;
  double *state_oldu_21;
  double *state_oldv_21;
  double *state_oldjab_21;
  double *state_oldjab5_21;
  double *state_oldjab6_21;
  double *state_oldjab7_21;
  double *state_olduc_21;
  double *state_oldvc_21;
  double *state_newh_21;
  double *state_newu_21;
  double *state_newv_21;
  double *state_newjab_21;
  double *state_newjab5_21;
  double *state_newjab6_21;
  double *state_newjab7_21;
  double *state_newuc_21;
  double *state_newvc_21;
} updateState_0_3_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_22;
  double *state_oldu_22;
  double *state_oldv_22;
  double *state_oldjab_22;
  double *state_oldjab5_22;
  double *state_oldjab6_22;
  double *state_oldjab7_22;
  double *state_olduc_22;
  double *state_oldvc_22;
  double *state_newh_22;
  double *state_newu_22;
  double *state_newv_22;
  double *state_newjab_22;
  double *state_newjab5_22;
  double *state_newjab6_22;
  double *state_newjab7_22;
  double *state_newuc_22;
  double *state_newvc_22;
} updateState_0_4_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_23;
  double *state_oldu_23;
  double *state_oldv_23;
  double *state_oldjab_23;
  double *state_oldjab5_23;
  double *state_oldjab6_23;
  double *state_oldjab7_23;
  double *state_olduc_23;
  double *state_oldvc_23;
  double *state_newh_23;
  double *state_newu_23;
  double *state_newv_23;
  double *state_newjab_23;
  double *state_newjab5_23;
  double *state_newjab6_23;
  double *state_newjab7_23;
  double *state_newuc_23;
  double *state_newvc_23;
} updateState_0_5_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_31;
  double *state_oldu_31;
  double *state_oldv_31;
  double *state_oldjab_31;
  double *state_oldjab5_31;
  double *state_oldjab6_31;
  double *state_oldjab7_31;
  double *state_olduc_31;
  double *state_oldvc_31;
  double *state_newh_31;
  double *state_newu_31;
  double *state_newv_31;
  double *state_newjab_31;
  double *state_newjab5_31;
  double *state_newjab6_31;
  double *state_newjab7_31;
  double *state_newuc_31;
  double *state_newvc_31;
} updateState_0_6_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_32;
  double *state_oldu_32;
  double *state_oldv_32;
  double *state_oldjab_32;
  double *state_oldjab5_32;
  double *state_oldjab6_32;
  double *state_oldjab7_32;
  double *state_olduc_32;
  double *state_oldvc_32;
  double *state_newh_32;
  double *state_newu_32;
  double *state_newv_32;
  double *state_newjab_32;
  double *state_newjab5_32;
  double *state_newjab6_32;
  double *state_newjab7_32;
  double *state_newuc_32;
  double *state_newvc_32;
} updateState_0_7_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_33;
  double *state_oldu_33;
  double *state_oldv_33;
  double *state_oldjab_33;
  double *state_oldjab5_33;
  double *state_oldjab6_33;
  double *state_oldjab7_33;
  double *state_olduc_33;
  double *state_oldvc_33;
  double *state_newh_33;
  double *state_newu_33;
  double *state_newv_33;
  double *state_newjab_33;
  double *state_newjab5_33;
  double *state_newjab6_33;
  double *state_newjab7_33;
  double *state_newuc_33;
  double *state_newvc_33;
} updateState_0_8_info;


typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_31;
  double *statejab5_31;
  double *stateh_31;
  double *statejab_31;
  double *stateuc_11;
  double *stateh_11;
  double *stateu_31;
  double *statev_31;
  double *statevc_31;
  double *statejab_11;
  double *stateu_11;
  double *statev_11;
  double *statevc_11;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateX_0_30_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_31;
  double *statejab5_31;
  double *stateh_31;
  double *statejab_31;
  double *stateh_11;
  double *stateh_21;
  double *stateuc_11;
  double *stateuc_21;
  double *tendfh_2;
  double *tendqh_2;
} updateX_0_31_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_31;
  double *statejab5_31;
  double *stateh_31;
  double *statejab_31;
  double *stateu_11;
  double *stateu_21;
  double *stateu_31;
  double *stateh_11;
  double *statejab_11;
  double *stateuc_11;
  double *statev_11;
  double *statevc_11;
  double *stateh_21;
  double *statejab_21;
  double *stateuc_21;
  double *statev_21;
  double *statevc_21;
  double *statev_31;
  double *statevc_31;
  double *tendfu_2;
  double *tendqu_2;
} updateX_0_32_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_31;
  double *statejab5_31;
  double *stateh_31;
  double *statejab_31;
  double *statev_11;
  double *statev_21;
  double *statev_31;
  double *tendfv_2;
  double *tendqv_2;
} updateX_0_33_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqv_2;
  double *tendqv_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_11;
  double *tendfu_1;
  double *statevc_21;
  double *statevc_31;
  double *tendfv_2;
  double *stateuc_11;
  double *tendfv_1;
  double *stateuc_21;
  double *stateuc_31;
  double *tenddxh_11;
  double *tenddxh_21;
  double *tenddxh_31;
  double *tenddxu_11;
  double *tenddxu_21;
  double *tenddxu_31;
  double *tenddxv_11;
  double *tenddxv_21;
  double *tenddxv_31;
} updateX_0_34_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_32;
  double *statejab5_32;
  double *stateh_32;
  double *statejab_32;
  double *stateuc_12;
  double *stateh_12;
  double *stateu_32;
  double *statev_32;
  double *statevc_32;
  double *statejab_12;
  double *stateu_12;
  double *statev_12;
  double *statevc_12;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateX_0_35_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_32;
  double *statejab5_32;
  double *stateh_32;
  double *statejab_32;
  double *stateh_12;
  double *stateh_22;
  double *stateuc_12;
  double *stateuc_22;
  double *tendfh_2;
  double *tendqh_2;
} updateX_0_36_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_32;
  double *statejab5_32;
  double *stateh_32;
  double *statejab_32;
  double *stateu_12;
  double *stateu_22;
  double *stateu_32;
  double *stateh_12;
  double *statejab_12;
  double *stateuc_12;
  double *statev_12;
  double *statevc_12;
  double *stateh_22;
  double *statejab_22;
  double *stateuc_22;
  double *statev_22;
  double *statevc_22;
  double *statev_32;
  double *statevc_32;
  double *tendfu_2;
  double *tendqu_2;
} updateX_0_37_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_32;
  double *statejab5_32;
  double *stateh_32;
  double *statejab_32;
  double *statev_12;
  double *statev_22;
  double *statev_32;
  double *tendfv_2;
  double *tendqv_2;
} updateX_0_38_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqv_2;
  double *tendqv_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_12;
  double *tendfu_1;
  double *statevc_22;
  double *statevc_32;
  double *tendfv_2;
  double *stateuc_12;
  double *tendfv_1;
  double *stateuc_22;
  double *stateuc_32;
  double *tenddxh_12;
  double *tenddxh_22;
  double *tenddxh_32;
  double *tenddxu_12;
  double *tenddxu_22;
  double *tenddxu_32;
  double *tenddxv_12;
  double *tenddxv_22;
  double *tenddxv_32;
} updateX_0_39_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_33;
  double *statejab5_33;
  double *stateh_33;
  double *statejab_33;
  double *stateuc_13;
  double *stateh_13;
  double *stateu_33;
  double *statev_33;
  double *statevc_33;
  double *statejab_13;
  double *stateu_13;
  double *statev_13;
  double *statevc_13;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateX_0_40_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_33;
  double *statejab5_33;
  double *stateh_33;
  double *statejab_33;
  double *stateh_13;
  double *stateh_23;
  double *stateuc_13;
  double *stateuc_23;
  double *tendfh_2;
  double *tendqh_2;
} updateX_0_41_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_33;
  double *statejab5_33;
  double *stateh_33;
  double *statejab_33;
  double *stateu_13;
  double *stateu_23;
  double *stateu_33;
  double *stateh_13;
  double *statejab_13;
  double *stateuc_13;
  double *statev_13;
  double *statevc_13;
  double *stateh_23;
  double *statejab_23;
  double *stateuc_23;
  double *statev_23;
  double *statevc_23;
  double *statev_33;
  double *statevc_33;
  double *tendfu_2;
  double *tendqu_2;
} updateX_0_42_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *stateuc_33;
  double *statejab5_33;
  double *stateh_33;
  double *statejab_33;
  double *statev_13;
  double *statev_23;
  double *statev_33;
  double *tendfv_2;
  double *tendqv_2;
} updateX_0_43_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqv_2;
  double *tendqv_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_13;
  double *tendfu_1;
  double *statevc_23;
  double *statevc_33;
  double *tendfv_2;
  double *stateuc_13;
  double *tendfv_1;
  double *stateuc_23;
  double *stateuc_33;
  double *tenddxh_13;
  double *tenddxh_23;
  double *tenddxh_33;
  double *tenddxu_13;
  double *tenddxu_23;
  double *tenddxu_33;
  double *tenddxv_13;
  double *tenddxv_23;
  double *tenddxv_33;
} updateX_0_44_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_13;
  double *statejab7_13;
  double *stateh_13;
  double *statejab_13;
  double *statevc_11;
  double *stateh_11;
  double *stateu_13;
  double *stateu_11;
  double *stateuc_13;
  double *statev_13;
  double *statejab_11;
  double *stateuc_11;
  double *statev_11;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateY_0_30_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_13;
  double *statejab7_13;
  double *stateh_13;
  double *statejab_13;
  double *stateh_11;
  double *stateh_12;
  double *statevc_11;
  double *statevc_12;
  double *tendfh_2;
  double *tendqh_2;
} updateY_0_31_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_13;
  double *statejab7_13;
  double *stateh_13;
  double *statejab_13;
  double *stateu_11;
  double *stateu_12;
  double *stateu_13;
  double *tendfu_2;
  double *tendqu_2;
} updateY_0_32_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_13;
  double *statejab7_13;
  double *stateh_13;
  double *statejab_13;
  double *statev_11;
  double *statev_12;
  double *statev_13;
  double *stateh_11;
  double *statejab_11;
  double *stateu_11;
  double *stateuc_11;
  double *statevc_11;
  double *stateh_12;
  double *statejab_12;
  double *stateu_12;
  double *stateuc_12;
  double *statevc_12;
  double *stateu_13;
  double *stateuc_13;
  double *tendfv_2;
  double *tendqv_2;
} updateY_0_33_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqu_2;
  double *tendqu_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_11;
  double *tendfu_1;
  double *statevc_12;
  double *statevc_13;
  double *tendfv_2;
  double *stateuc_11;
  double *tendfv_1;
  double *stateuc_12;
  double *stateuc_13;
  double *tenddyh_11;
  double *tenddyh_12;
  double *tenddyh_13;
  double *tenddyu_11;
  double *tenddyu_12;
  double *tenddyu_13;
  double *tenddyv_11;
  double *tenddyv_12;
  double *tenddyv_13;
} updateY_0_34_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_23;
  double *statejab7_23;
  double *stateh_23;
  double *statejab_23;
  double *statevc_21;
  double *stateh_21;
  double *stateu_23;
  double *stateu_21;
  double *stateuc_23;
  double *statev_23;
  double *statejab_21;
  double *stateuc_21;
  double *statev_21;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateY_0_35_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_23;
  double *statejab7_23;
  double *stateh_23;
  double *statejab_23;
  double *stateh_21;
  double *stateh_22;
  double *statevc_21;
  double *statevc_22;
  double *tendfh_2;
  double *tendqh_2;
} updateY_0_36_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_23;
  double *statejab7_23;
  double *stateh_23;
  double *statejab_23;
  double *stateu_21;
  double *stateu_22;
  double *stateu_23;
  double *tendfu_2;
  double *tendqu_2;
} updateY_0_37_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_23;
  double *statejab7_23;
  double *stateh_23;
  double *statejab_23;
  double *statev_21;
  double *statev_22;
  double *statev_23;
  double *stateh_21;
  double *statejab_21;
  double *stateu_21;
  double *stateuc_21;
  double *statevc_21;
  double *stateh_22;
  double *statejab_22;
  double *stateu_22;
  double *stateuc_22;
  double *statevc_22;
  double *stateu_23;
  double *stateuc_23;
  double *tendfv_2;
  double *tendqv_2;
} updateY_0_38_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqu_2;
  double *tendqu_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_21;
  double *tendfu_1;
  double *statevc_22;
  double *statevc_23;
  double *tendfv_2;
  double *stateuc_21;
  double *tendfv_1;
  double *stateuc_22;
  double *stateuc_23;
  double *tenddyh_11;
  double *tenddyh_12;
  double *tenddyh_13;
  double *tenddyu_11;
  double *tenddyu_12;
  double *tenddyu_13;
  double *tenddyv_11;
  double *tenddyv_12;
  double *tenddyv_13;
} updateY_0_39_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_33;
  double *statejab7_33;
  double *stateh_33;
  double *statejab_33;
  double *statevc_31;
  double *stateh_31;
  double *stateu_33;
  double *stateu_31;
  double *stateuc_33;
  double *statev_33;
  double *statejab_31;
  double *stateuc_31;
  double *statev_31;
  double *tendfh_1;
  double *tendfu_1;
  double *tendfv_1;
  double *tendqh_1;
  double *tendqu_1;
  double *tendqv_1;
} updateY_0_40_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_33;
  double *statejab7_33;
  double *stateh_33;
  double *statejab_33;
  double *stateh_31;
  double *stateh_32;
  double *statevc_31;
  double *statevc_32;
  double *tendfh_2;
  double *tendqh_2;
} updateY_0_41_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_33;
  double *statejab7_33;
  double *stateh_33;
  double *statejab_33;
  double *stateu_31;
  double *stateu_32;
  double *stateu_33;
  double *tendfu_2;
  double *tendqu_2;
} updateY_0_42_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *statevc_33;
  double *statejab7_33;
  double *stateh_33;
  double *statejab_33;
  double *statev_31;
  double *statev_32;
  double *statev_33;
  double *stateh_31;
  double *statejab_31;
  double *stateu_31;
  double *stateuc_31;
  double *statevc_31;
  double *stateh_32;
  double *statejab_32;
  double *stateu_32;
  double *stateuc_32;
  double *statevc_32;
  double *stateu_33;
  double *stateuc_33;
  double *tendfv_2;
  double *tendqv_2;
} updateY_0_43_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *tendqu_2;
  double *tendqu_1;
  double *tendfh_2;
  double *tendfh_1;
  double *tendfu_2;
  double *statevc_31;
  double *tendfu_1;
  double *statevc_32;
  double *statevc_33;
  double *tendfv_2;
  double *stateuc_31;
  double *tendfv_1;
  double *stateuc_32;
  double *stateuc_33;
  double *tenddyh_11;
  double *tenddyh_12;
  double *tenddyh_13;
  double *tenddyu_11;
  double *tenddyu_12;
  double *tenddyu_13;
  double *tenddyv_11;
  double *tenddyv_12;
  double *tenddyv_13;
} updateY_0_44_info;


typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_11;
  double *tend1dxh_11;
  double *tend1dyh_11;
  double *state_oldu_11;
  double *tend1dxu_11;
  double *tend1dyu_11;
  double *state_oldv_11;
  double *tend1dxv_11;
  double *tend1dyv_11;
  double *state_newh_11;
  double *state_newu_11;
  double *state_newv_11;
  double dt;
} update_rk1_0_0_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_12;
  double *tend1dxh_12;
  double *tend1dyh_12;
  double *state_oldu_12;
  double *tend1dxu_12;
  double *tend1dyu_12;
  double *state_oldv_12;
  double *tend1dxv_12;
  double *tend1dyv_12;
  double *state_newh_12;
  double *state_newu_12;
  double *state_newv_12;
  double dt;
} update_rk1_0_1_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_13;
  double *tend1dxh_13;
  double *tend1dyh_13;
  double *state_oldu_13;
  double *tend1dxu_13;
  double *tend1dyu_13;
  double *state_oldv_13;
  double *tend1dxv_13;
  double *tend1dyv_13;
  double *state_newh_13;
  double *state_newu_13;
  double *state_newv_13;
  double dt;
} update_rk1_0_2_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_21;
  double *tend1dxh_21;
  double *tend1dyh_21;
  double *state_oldu_21;
  double *tend1dxu_21;
  double *tend1dyu_21;
  double *state_oldv_21;
  double *tend1dxv_21;
  double *tend1dyv_21;
  double *state_newh_21;
  double *state_newu_21;
  double *state_newv_21;
  double dt;
} update_rk1_0_3_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_22;
  double *tend1dxh_22;
  double *tend1dyh_22;
  double *state_oldu_22;
  double *tend1dxu_22;
  double *tend1dyu_22;
  double *state_oldv_22;
  double *tend1dxv_22;
  double *tend1dyv_22;
  double *state_newh_22;
  double *state_newu_22;
  double *state_newv_22;
  double dt;
} update_rk1_0_4_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_23;
  double *tend1dxh_23;
  double *tend1dyh_23;
  double *state_oldu_23;
  double *tend1dxu_23;
  double *tend1dyu_23;
  double *state_oldv_23;
  double *tend1dxv_23;
  double *tend1dyv_23;
  double *state_newh_23;
  double *state_newu_23;
  double *state_newv_23;
  double dt;
} update_rk1_0_5_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_31;
  double *tend1dxh_31;
  double *tend1dyh_31;
  double *state_oldu_31;
  double *tend1dxu_31;
  double *tend1dyu_31;
  double *state_oldv_31;
  double *tend1dxv_31;
  double *tend1dyv_31;
  double *state_newh_31;
  double *state_newu_31;
  double *state_newv_31;
  double dt;
} update_rk1_0_6_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_32;
  double *tend1dxh_32;
  double *tend1dyh_32;
  double *state_oldu_32;
  double *tend1dxu_32;
  double *tend1dyu_32;
  double *state_oldv_32;
  double *tend1dxv_32;
  double *tend1dyv_32;
  double *state_newh_32;
  double *state_newu_32;
  double *state_newv_32;
  double dt;
} update_rk1_0_7_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_33;
  double *tend1dxh_33;
  double *tend1dyh_33;
  double *state_oldu_33;
  double *tend1dxu_33;
  double *tend1dyu_33;
  double *state_oldv_33;
  double *tend1dxv_33;
  double *tend1dyv_33;
  double *state_newh_33;
  double *state_newu_33;
  double *state_newv_33;
  double dt;
} update_rk1_0_8_info;


typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_11;
  double *tend1dxh_11;
  double *tend1dyh_11;
  double *state_oldu_11;
  double *tend1dxu_11;
  double *tend1dyu_11;
  double *state_oldv_11;
  double *tend1dxv_11;
  double *tend1dyv_11;
  double *tend2dxh_11;
  double *tend2dyh_11;
  double *tend2dxu_11;
  double *tend2dyu_11;
  double *tend2dxv_11;
  double *tend2dyv_11;
  double *state_newh_11;
  double *state_newu_11;
  double *state_newv_11;
  double dt;
} update_rk2_0_0_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_12;
  double *tend1dxh_12;
  double *tend1dyh_12;
  double *state_oldu_12;
  double *tend1dxu_12;
  double *tend1dyu_12;
  double *state_oldv_12;
  double *tend1dxv_12;
  double *tend1dyv_12;
  double *tend2dxh_12;
  double *tend2dyh_12;
  double *tend2dxu_12;
  double *tend2dyu_12;
  double *tend2dxv_12;
  double *tend2dyv_12;
  double *state_newh_12;
  double *state_newu_12;
  double *state_newv_12;
  double dt;
} update_rk2_0_1_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_13;
  double *tend1dxh_13;
  double *tend1dyh_13;
  double *state_oldu_13;
  double *tend1dxu_13;
  double *tend1dyu_13;
  double *state_oldv_13;
  double *tend1dxv_13;
  double *tend1dyv_13;
  double *tend2dxh_13;
  double *tend2dyh_13;
  double *tend2dxu_13;
  double *tend2dyu_13;
  double *tend2dxv_13;
  double *tend2dyv_13;
  double *state_newh_13;
  double *state_newu_13;
  double *state_newv_13;
  double dt;
} update_rk2_0_2_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_21;
  double *tend1dxh_21;
  double *tend1dyh_21;
  double *state_oldu_21;
  double *tend1dxu_21;
  double *tend1dyu_21;
  double *state_oldv_21;
  double *tend1dxv_21;
  double *tend1dyv_21;
  double *tend2dxh_21;
  double *tend2dyh_21;
  double *tend2dxu_21;
  double *tend2dyu_21;
  double *tend2dxv_21;
  double *tend2dyv_21;
  double *state_newh_21;
  double *state_newu_21;
  double *state_newv_21;
  double dt;
} update_rk2_0_3_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_22;
  double *tend1dxh_22;
  double *tend1dyh_22;
  double *state_oldu_22;
  double *tend1dxu_22;
  double *tend1dyu_22;
  double *state_oldv_22;
  double *tend1dxv_22;
  double *tend1dyv_22;
  double *tend2dxh_22;
  double *tend2dyh_22;
  double *tend2dxu_22;
  double *tend2dyu_22;
  double *tend2dxv_22;
  double *tend2dyv_22;
  double *state_newh_22;
  double *state_newu_22;
  double *state_newv_22;
  double dt;
} update_rk2_0_4_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_23;
  double *tend1dxh_23;
  double *tend1dyh_23;
  double *state_oldu_23;
  double *tend1dxu_23;
  double *tend1dyu_23;
  double *state_oldv_23;
  double *tend1dxv_23;
  double *tend1dyv_23;
  double *tend2dxh_23;
  double *tend2dyh_23;
  double *tend2dxu_23;
  double *tend2dyu_23;
  double *tend2dxv_23;
  double *tend2dyv_23;
  double *state_newh_23;
  double *state_newu_23;
  double *state_newv_23;
  double dt;
} update_rk2_0_5_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_31;
  double *tend1dxh_31;
  double *tend1dyh_31;
  double *state_oldu_31;
  double *tend1dxu_31;
  double *tend1dyu_31;
  double *state_oldv_31;
  double *tend1dxv_31;
  double *tend1dyv_31;
  double *tend2dxh_31;
  double *tend2dyh_31;
  double *tend2dxu_31;
  double *tend2dyu_31;
  double *tend2dxv_31;
  double *tend2dyv_31;
  double *state_newh_31;
  double *state_newu_31;
  double *state_newv_31;
  double dt;
} update_rk2_0_6_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_32;
  double *tend1dxh_32;
  double *tend1dyh_32;
  double *state_oldu_32;
  double *tend1dxu_32;
  double *tend1dyu_32;
  double *state_oldv_32;
  double *tend1dxv_32;
  double *tend1dyv_32;
  double *tend2dxh_32;
  double *tend2dyh_32;
  double *tend2dxu_32;
  double *tend2dyu_32;
  double *tend2dxv_32;
  double *tend2dyv_32;
  double *state_newh_32;
  double *state_newu_32;
  double *state_newv_32;
  double dt;
} update_rk2_0_7_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_33;
  double *tend1dxh_33;
  double *tend1dyh_33;
  double *state_oldu_33;
  double *tend1dxu_33;
  double *tend1dyu_33;
  double *state_oldv_33;
  double *tend1dxv_33;
  double *tend1dyv_33;
  double *tend2dxh_33;
  double *tend2dyh_33;
  double *tend2dxu_33;
  double *tend2dyu_33;
  double *tend2dxv_33;
  double *tend2dyv_33;
  double *state_newh_33;
  double *state_newu_33;
  double *state_newv_33;
  double dt;
} update_rk2_0_8_info;


typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_11;
  double *tend1dxh_11;
  double *tend1dyh_11;
  double *state_oldu_11;
  double *tend1dxu_11;
  double *tend1dyu_11;
  double *state_oldv_11;
  double *tend1dxv_11;
  double *tend1dyv_11;
  double *tend2dxh_11;
  double *tend2dyh_11;
  double *tend3dxh_11;
  double *tend3dyh_11;
  double *tend2dxu_11;
  double *tend2dyu_11;
  double *tend3dxu_11;
  double *tend3dyu_11;
  double *tend2dxv_11;
  double *tend2dyv_11;
  double *tend3dxv_11;
  double *tend3dyv_11;
  double *state_newh_11;
  double *state_newu_11;
  double *state_newv_11;
  double dt;
} update_rk3_0_0_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_12;
  double *tend1dxh_12;
  double *tend1dyh_12;
  double *state_oldu_12;
  double *tend1dxu_12;
  double *tend1dyu_12;
  double *state_oldv_12;
  double *tend1dxv_12;
  double *tend1dyv_12;
  double *tend2dxh_12;
  double *tend2dyh_12;
  double *tend3dxh_12;
  double *tend3dyh_12;
  double *tend2dxu_12;
  double *tend2dyu_12;
  double *tend3dxu_12;
  double *tend3dyu_12;
  double *tend2dxv_12;
  double *tend2dyv_12;
  double *tend3dxv_12;
  double *tend3dyv_12;
  double *state_newh_12;
  double *state_newu_12;
  double *state_newv_12;
  double dt;
} update_rk3_0_1_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_13;
  double *tend1dxh_13;
  double *tend1dyh_13;
  double *state_oldu_13;
  double *tend1dxu_13;
  double *tend1dyu_13;
  double *state_oldv_13;
  double *tend1dxv_13;
  double *tend1dyv_13;
  double *tend2dxh_13;
  double *tend2dyh_13;
  double *tend3dxh_13;
  double *tend3dyh_13;
  double *tend2dxu_13;
  double *tend2dyu_13;
  double *tend3dxu_13;
  double *tend3dyu_13;
  double *tend2dxv_13;
  double *tend2dyv_13;
  double *tend3dxv_13;
  double *tend3dyv_13;
  double *state_newh_13;
  double *state_newu_13;
  double *state_newv_13;
  double dt;
} update_rk3_0_2_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_21;
  double *tend1dxh_21;
  double *tend1dyh_21;
  double *state_oldu_21;
  double *tend1dxu_21;
  double *tend1dyu_21;
  double *state_oldv_21;
  double *tend1dxv_21;
  double *tend1dyv_21;
  double *tend2dxh_21;
  double *tend2dyh_21;
  double *tend3dxh_21;
  double *tend3dyh_21;
  double *tend2dxu_21;
  double *tend2dyu_21;
  double *tend3dxu_21;
  double *tend3dyu_21;
  double *tend2dxv_21;
  double *tend2dyv_21;
  double *tend3dxv_21;
  double *tend3dyv_21;
  double *state_newh_21;
  double *state_newu_21;
  double *state_newv_21;
  double dt;
} update_rk3_0_3_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_22;
  double *tend1dxh_22;
  double *tend1dyh_22;
  double *state_oldu_22;
  double *tend1dxu_22;
  double *tend1dyu_22;
  double *state_oldv_22;
  double *tend1dxv_22;
  double *tend1dyv_22;
  double *tend2dxh_22;
  double *tend2dyh_22;
  double *tend3dxh_22;
  double *tend3dyh_22;
  double *tend2dxu_22;
  double *tend2dyu_22;
  double *tend3dxu_22;
  double *tend3dyu_22;
  double *tend2dxv_22;
  double *tend2dyv_22;
  double *tend3dxv_22;
  double *tend3dyv_22;
  double *state_newh_22;
  double *state_newu_22;
  double *state_newv_22;
  double dt;
} update_rk3_0_4_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_23;
  double *tend1dxh_23;
  double *tend1dyh_23;
  double *state_oldu_23;
  double *tend1dxu_23;
  double *tend1dyu_23;
  double *state_oldv_23;
  double *tend1dxv_23;
  double *tend1dyv_23;
  double *tend2dxh_23;
  double *tend2dyh_23;
  double *tend3dxh_23;
  double *tend3dyh_23;
  double *tend2dxu_23;
  double *tend2dyu_23;
  double *tend3dxu_23;
  double *tend3dyu_23;
  double *tend2dxv_23;
  double *tend2dyv_23;
  double *tend3dxv_23;
  double *tend3dyv_23;
  double *state_newh_23;
  double *state_newu_23;
  double *state_newv_23;
  double dt;
} update_rk3_0_5_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_31;
  double *tend1dxh_31;
  double *tend1dyh_31;
  double *state_oldu_31;
  double *tend1dxu_31;
  double *tend1dyu_31;
  double *state_oldv_31;
  double *tend1dxv_31;
  double *tend1dyv_31;
  double *tend2dxh_31;
  double *tend2dyh_31;
  double *tend3dxh_31;
  double *tend3dyh_31;
  double *tend2dxu_31;
  double *tend2dyu_31;
  double *tend3dxu_31;
  double *tend3dyu_31;
  double *tend2dxv_31;
  double *tend2dyv_31;
  double *tend3dxv_31;
  double *tend3dyv_31;
  double *state_newh_31;
  double *state_newu_31;
  double *state_newv_31;
  double dt;
} update_rk3_0_6_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_32;
  double *tend1dxh_32;
  double *tend1dyh_32;
  double *state_oldu_32;
  double *tend1dxu_32;
  double *tend1dyu_32;
  double *state_oldv_32;
  double *tend1dxv_32;
  double *tend1dyv_32;
  double *tend2dxh_32;
  double *tend2dyh_32;
  double *tend3dxh_32;
  double *tend3dyh_32;
  double *tend2dxu_32;
  double *tend2dyu_32;
  double *tend3dxu_32;
  double *tend3dyu_32;
  double *tend2dxv_32;
  double *tend2dyv_32;
  double *tend3dxv_32;
  double *tend3dyv_32;
  double *state_newh_32;
  double *state_newu_32;
  double *state_newv_32;
  double dt;
} update_rk3_0_7_info;

typedef struct{
  int lx, ly, lz;
  int ox, oy, oz;
  int hx, hy, hz;
  int bx, by, bz;
  int mx, my, mz;
  double *state_oldh_33;
  double *tend1dxh_33;
  double *tend1dyh_33;
  double *state_oldu_33;
  double *tend1dxu_33;
  double *tend1dyu_33;
  double *state_oldv_33;
  double *tend1dxv_33;
  double *tend1dyv_33;
  double *tend2dxh_33;
  double *tend2dyh_33;
  double *tend3dxh_33;
  double *tend3dyh_33;
  double *tend2dxu_33;
  double *tend2dyu_33;
  double *tend3dxu_33;
  double *tend3dyu_33;
  double *tend2dxv_33;
  double *tend2dyv_33;
  double *tend3dxv_33;
  double *tend3dyv_33;
  double *state_newh_33;
  double *state_newu_33;
  double *state_newv_33;
  double dt;
} update_rk3_0_8_info;


